### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by stef-levesque** [pr0g/switch-corresponding#1]
The extension will fail when provided with a file path using '\' (like on Windows)

Using the following should solve the problem

```javascript
var path = require('path');
var fileNameAndExtension = path.basename(filePath);
```

**Comment by pr0g** [comment]
Oh crap good find! Sorry total schoolboy error there! I will fix that asap. Cheers!

**Comment by pr0g** [comment]
This should be fixed now - thanks for the suggested fix. I haven't been able to test on Windows unfortunately (poor form I know but I don't have a windows machine atm - El Capitan broken my bootcamp partition... anyway I digress, if you could please grab the latest version and give that a test that'd be amazing!

Thanks again! :+1: :)

**Comment by pr0g** [comment]
I should have consulted this - https://gist.github.com/domenic/2790533#paths-and-urls :stuck_out_tongue_closed_eyes: 

Cheers! :+1:

**Comment by stef-levesque** [comment]
Works now, thanks !
btw, useful extension :smiley:

**Comment by pr0g** [comment]
Awesome glad to hear!! :smile: Not at all! Thanks for letting me know about the problem!
