### ISSUE TITLE
Doesn't open in the window expected when using split screen

### ISSUE THREAD

**Issue by zethon** [pr0g/switch-corresponding#6]
If you open up multiple files in a split screen and set focus on the window on the right (for example) and the hit your shortcut to go to the header/cpp file, the file will appear in the window on the left, instead of the right (the window that has focus).

Perhaps this behavior should be configurable.

**Comment by pr0g** [comment]
Ah good spot! That's something I hadn't thought of, I'll see if I can have a look into it! 

I imagine the behaviour should be to open the file in the same window, unless the file is already open in another window... hmm not sure. Not certain if the api provides support for this but I'll take a look. 

Cheers!

**Comment by zabel-xyz** [comment]
In the method 'showTextDocument` there is a parameter ViewColumn to specify in which column to open (1,2,3). 
(see https://github.com/Microsoft/vscode/issues/8667)
To force a new editor, perhaps you can use the command 
vscode.commands.executeCommand("workbench.action.splitEditor") before showTextDocument.

**Comment by pr0g** [comment]
Hey there,

I just thought I'd have a quick look at this but it seems the property to see which column has current focus isn't working?

I am attempting to use - `vscode.window.activeTextEditor.viewColumn` but viewColumn is not available (autocomplete doesn't find it and can't build the code trying to use it). Do you know if this functionality was removed or am I looking for it in the wrong place.

Looks like it should be there:

<img width="787" alt="screen shot 2016-07-16 at 15 44 04" src="https://cloud.githubusercontent.com/assets/1136625/16895390/8fe91d6a-4b6c-11e6-896b-02799e469305.png">

Thanks!

**Comment by zabel-xyz** [comment]
Perhaps, you must use a more recent version of vscode.
I use it in my extension local-history and it works well.
(It works better now: if the column doesn't exist, vscode create it.)

`vscode.window.showTextDocument(d, vscode.window.activeTextEditor.viewColumn)`
(to show in the same column)
`vscode.window.showTextDocument(d, Math.min(vscode.window.activeTextEditor.viewColumn + 1, 3))`
(to show in the next column, side by side)

**Comment by pr0g** [comment]
Hey Zabel!

You were quite right! My package.json file was depending on a very out of date of version of vscode! Updated it and low and behold viewColumn showed up! 😄 

This has now been fixed and published! Version 0.0.8 should now be available with correct column switching! 

Thank you both!

Cheers!


Tom
